name = "photos-saver-backend"
main = "src/worker.ts"
compatibility_date = "2026-02-27"

[observability]
enabled = true

[vars]
GOOGLE_CLIENT_ID = "478240865692-hqht6c29pg3lspglq2hbtc95djiakj7u.apps.googleusercontent.com"
GOOGLE_OAUTH_REDIRECT_URI = "https://photos-saver.anas-alqoyyum.workers.dev/v1/auth/callback"
CORS_ORIGIN = "*"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "ae52b3c57afa4269bda449933cba0424"

[[d1_databases]]
binding = "APP_DB"
database_name = "APP_DB"
database_id = "11cdf975-13b9-4bfa-846b-7e5f47616687"
migrations_dir = "migrations"
